work in progress

diff --git a/acetoscan b/acetoscan
--- a/acetoscan
+++ b/acetoscan
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # File: AcetoScan
-# Last modified: ons maj 08, 2019  03:38
+# Last modified: mån maj 13, 2019  01:07
 # Sign: JN
 
 set -euo pipefail
@@ -43,6 +43,11 @@ Forward reads files must be *_R1_001.fastq.gz format
 echo "¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤"
 
 ###    getting current working directory
+# TODO: Since the INPUT_DATA and OUTPUT_DATA folders are created by the script,
+# there is no reason for making sure the cwd is the "AcetoScan direcory". The
+# only issue to solve is to make sure the helper scripts in "SCRIPTS" are found:
+# Find a good way to add them to the PATH!
+
 export CDIR=$(pwd)
 #set -e
 
@@ -82,7 +87,7 @@ else
     echo "" > /dev/null
 fi
 
-###    setting woring directory according to user input
+###    setting working directory according to user input
 if [ "${REP_1}" == "y" ]; then
     echo "" > /dev/null
 else
@@ -123,14 +128,18 @@ fi
 THREADS=$(nproc 2> /dev/null || sysctl -n hw.ncpu 2> /dev/null || getconf _NPROCESSORS_ONLN 2> /dev/null)
 
 ###    Removing old directories
-# TODO: Check for presence before delete
+# TODO: Check (and warn?) for presence before delete?
 rm -rf "${CDIR}/INPUT_DATA"
 rm -rf "${CDIR}/OUTPUT_DATA"
 rm -rf "${CDIR}/ACETOSCAN_RESULT"
 
 ###    find illumina raw reads and making soft links to the data
 mkdir -v -p "${CDIR}/INPUT_DATA"
-cd "${CDIR}/INPUT_DATA/"
+if ! cd "${CDIR}/INPUT_DATA/" ; then
+    echo "Error: could not cd to ${CDIR}/INPUT_DATA/"
+    exit 1
+fi
+
 find "${READ_PATH}" -name '*_R1_001.fastq.gz' -exec ln -s {} "${CDIR}/INPUT_DATA/" \; 2> /dev/null
 
 ###    Checking if link exist
@@ -138,7 +147,6 @@ if [ ! -n "$(find "${CDIR}/INPUT_DATA/" -maxdepth 1 -type l -name '*_R1_001.fast
     echo "Input files \"*_R1_001.fastq.gz\" not found in ${CDIR}/INPUT_DATA/, Aborting !!!"
     exit 1
 fi
-
 
 ###    Adapter trimming and quality filtering of the raw reads
 # TODO: make sure the trimmed folder is created by mother script,
@@ -148,13 +156,22 @@ mkdir -p "${CDIR}/OUTPUT_DATA/trimmed/FASTA"
 echo ""
 echo "Performing adapters trimming and quality filtering"
 
-cutadapt_illumina.sh # <================= external script
+cutadapt_illumina2.sh # <================= external script
+#cutadapt_illumina.sh # <================= external script
 #bash "${CDIR}/SCRIPTS/cutadapt_illumina.sh" # <================= external script
 
-echo "Cutadapt report: -->> cutadapt.out in ${CDIR}/OUTPUT_DATA/"
+if [ -e "${CDIR}/OUTPUT_DATA/cutadapt.out" ]; then
+    echo "Cutadapt report: -->> cutadapt.out in ${CDIR}/OUTPUT_DATA/"
+else
+    echo "Error! Cutadapt report cutadapt.out not found in ${CDIR}/OUTPUT_DATA/"
+    exit 1
+fi
 
 ###    Unzipping and preparing variables file
-cd "${CDIR}/OUTPUT_DATA/trimmed"
+if ! cd "${CDIR}/OUTPUT_DATA/trimmed" ; then
+    echo "Error: could not cd to ${CDIR}/OUTPUT_DATA/trimmed"
+    exit 1
+fi
 
 # Begin fastq2fasta
 # TODO: stub for alternative fastq.gz to fasta conversion
@@ -199,7 +216,10 @@ find "${CDIR}/OUTPUT_DATA/trimmed" -name '*_trimmed_R1.fastq.gz' \
 
     ###    Longest best frame analysis
     # preparing variable file
-    cd "${CDIR}/OUTPUT_DATA/trimmed/FASTA"
+    if ! cd "${CDIR}/OUTPUT_DATA/trimmed/FASTA" ; then
+        echo "Error: could not cd to ${CDIR}/OUTPUT_DATA/trimmed/FASTA"
+        exit 1
+    fi
 
     # TODO: use find or shell expansion instead of ls and cat
     ls *trimmed_R1.fasta > FRAME_INPUTfile.txt
@@ -341,10 +361,10 @@ echo ""
 #     "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/FTHFS_OTU_table.pre" | \
 #    sort -n > "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/FTHFS_OTU_table.txt"
 cat "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/FTHFS_OTU_table.pre" | \
-    sed 's/#OTU ID/ID/' | \
-    sed 's/OTU_//' | \
+    sed -e 's/#OTU ID/ID/' | \
+    sed -e 's/OTU_//' | \
     sort -n | \
-    sed 's/^/OTU_/' > "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/FTHFS_OTU_table.txt"
+    sed -e 's/^/OTU_/' > "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/FTHFS_OTU_table.txt"
 
 ###    Assigning taxonomy 
 echo ""
@@ -363,7 +383,7 @@ blastx \
     -outfmt "6 qseqid saccver pident"
 
 ###    Preparing OTU taxonomy table
-sed 's/;tax=/,/g' "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/OTUblast.txt.tmp" | \
+sed -e 's/;tax=/,/g' "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/OTUblast.txt.tmp" | \
     sed '1s/^/#OTU,Subject_Accession,Kingdom,Phylum,Class,Order,Family,Genus,Species,Percentage_identity\n/' > "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/FTHFS_TAX_table_pre"
 
 #    making tab to comma
@@ -372,14 +392,22 @@ sed -e 's/\t/,/g' "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/FTHFS_TAX_table_pre
 ###    Translating OTU nucleotide sequence to Amino acid based on best frame analysis
 rm -rf "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/Translation"
 mkdir -p "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/Translation"
-cd "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/Translation"
+if ! cd "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/Translation" ; then
+    echo "Error: could not cd to ${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/Translation"
+    exit 1
+fi
 cp "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/FTHFS_OTU.fasta" .
 
 Translation_LBF.sh FTHFS_OTU.fasta  # <============== external script
 #bash "${CDIR}/SCRIPTS/Translation_LBF.sh" FTHFS_OTU.fasta  # <============== external script
 
 ###    fixing taxonomy to OTU fasta header 
-cd "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/"
+cd "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/" || echo "Error: could not cd to !$" && exit 1
+if ! cd "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/" ; then
+    echo "Error: could not cd to ${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/"
+    exit 1
+fi
+
 # TODO: no need for cat
 #cat OTUblast.txt.tmp | sed 's/;tax=/\t/g' | \
 #    awk -F "\t" '{print $1,$3,$4}' | \
@@ -400,7 +428,10 @@ cat "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/FTHFS_OTU_table.txt" > "${CDIR}/O
 
 ###    R analysis
 mkdir -p "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/VISUALIZATION"
-cd "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/VISUALIZATION"
+if ! cd "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/VISUALIZATION" ; then
+    echo "Error: could not cd to ${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/VISUALIZATION"
+    exit 1
+fi
 cp "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/FTHFS_OTU_table_R.txt" .
 cp "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/FTHFS_TAX_table_R.txt" .
 
@@ -421,7 +452,11 @@ echo -e "\n\n\n"
 
 ###    Putting everything together in a Result DIRECTORY
 mkdir -p "${CDIR}/ACETOSCAN_RESULT"
-cd "${CDIR}/ACETOSCAN_RESULT"
+cd "${CDIR}/ACETOSCAN_RESULT" || echo "Error: could not cd to !$" && exit 1
+if ! cd "${CDIR}/ACETOSCAN_RESULT" ; then
+    echo "Error: could not cd to ${CDIR}/ACETOSCAN_RESULT"
+    exit 1
+fi
 cp "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/FTHFS_OTU.fasta" .
 cp "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/FTHFS_OTU_table.txt" .
 cp "${CDIR}/OUTPUT_DATA/trimmed/FASTA/VSEARCH/FTHFS_TAX_table_full.csv" .
