Update acetoscan

diff --git a/acetoscan b/acetoscan
--- a/acetoscan
+++ b/acetoscan
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-# File: AcetoScan
-# Last modified: Ons Feb 06, 2020 20:33
+# File: acetoscan
+# Last modified: Wed, Mar 11, 2020 19:00
 # Sign: Abhi
 
 ### Setting colour variables
@@ -29,6 +29,7 @@ echo -e "${LRED}\
 |___________________________________________________________|
 ${RESTORE}\n#\t${YELLOW}©Abhijeet Singh${RESTORE}
 #\t${YELLOW}-abhijeetsingh.aau@gmail.com${RESTORE}
+#\t${YELLOW}-acetoscan version - 1.0${RESTORE}
 "
 
 ###    Recording the time whent he script was started
@@ -37,7 +38,11 @@ start=$(date +%s) #start time of script
 
 ###	Variable for the backup
 
-DATE=$(date | sed 's/ /_/g;s/:/-/g;s/__/_/g' )
+DATE=$(date +"%F_%r" | sed 's/:/_/g;s/ //g;s/-//g')
+
+###     Username
+
+user=`echo ${SUDO_USER:-${USER}}`
 
 ###     Setting up variables
 
@@ -49,12 +54,9 @@ min_len=""
 qual=""            
 cluster_threshold=""
 cluster_size=""
+evalue=""
 
-###     Username
-
-user=`echo ${SUDO_USER:-${USER}}`
-
-###     Defaults
+###     Defaults variables
 
 output_dir_def="/home/$user/acetoscan/output_data"
 read_type_def="1"
@@ -63,7 +65,8 @@ min_len_def="120"
 qual_def="20" 
 cluster_threshold_def="0.80"
 cluster_size_def="2"
-version_def="0.1.0"
+version_def="1.0"
+evalue_def="1e-3"
 
 ###    Getting processors information
 
@@ -74,14 +77,14 @@ THREADS=$(nproc 2> /dev/null || sysctl -n hw.ncpu 2> /dev/null || getconf _NPROC
 #       function
 
 usage() {
-echo "Usage   : $0 [-i <input directory>] [-o <output directory>] [-m <max_length>] [-n <min_length>] [-q <quality threshold>] [-r <reads type>] [-t <clustering threshold>] [-c <min_cluster size>]
-Example : acetoscan -i /<input path>/ -o /<output path>/ -m 300 -n 120 -q 20 -r 1 -t 0.80 -c 2" 1>&2; exit 1;
+echo "Usage   : $0 [-i <input directory>] [-o <output directory>] [-m <max_length>] [-n <min_length>] [-q <quality threshold>] [-r <reads type>] [-t <clustering threshold>] [-c <min_cluster size>] [-e <E-value>]
+Example : acetoscan -i /<input path>/ -o /<output path>/ -m 300 -n 120 -q 20 -r 1 -t 0.80 -c 2 -e 1e-3" 1>&2; exit 1;
 }
 
 
 #       flags
 
-while getopts "i:o:m:n:q:r:t:c:hv" flags; 
+while getopts "i:o:m:n:q:r:t:c:e:hvCX" flags; 
         do      
                 case "${flags}" in
                         
@@ -116,10 +119,14 @@ while getopts "i:o:m:n:q:r:t:c:hv" flags;
                         c)
                                 cluster_size=${OPTARG}
                                 ;;
+                                
+                        e)
+                                evalue=${OPTARG}
+                                ;;
 
                         h)
                                 echo "
-Example : acetoscan -i /<input path>/ -o /<output path>/ -m 300 -n 120 -q 20 -r 1 -t 0.80 -c 2
+Example : acetoscan -i /<input path>/ -o /<output path>/ -m 300 -n 120 -q 20 -r 1 -t 0.80 -c 2 -e 1e-3
 
         -i      Input directory containing raw illumina data
         -o      Output directory
@@ -137,8 +144,12 @@ Example : acetoscan -i /<input path>/ -o /<output path>/ -m 300 -n 120 -q 20 -r 
                         :default cluster threshold = 0.80 (80 %)
         -c      Minimum cluster size
                         :default minimum cluster size = 2
-        -h      print Help
-        -v      print acetoscan version"
+        -e      E-value
+                        :default evalue = 1e-3
+        -h      Print help        
+        -X      Print AcetoScan commands
+        -v      Print AcetoScan version
+        -C      Print AcetoScan citation"
                                 exit                                
                                 ;;
 
@@ -147,6 +158,31 @@ Example : acetoscan -i /<input path>/ -o /<output path>/ -m 300 -n 120 -q 20 -r 
                                 echo -e "#\tVisit \"${YELLOW}https://acetobase.molbio.slu.se/${RESTORE}\" for more information."
                                 exit
                                 ;;
+                                
+                        C)
+                                echo -e "#\tCitations: If you use ${YELLOW}AcetoScan pipeline${RESTORE}, please cite as:\n"
+                                echo -e "#\tAcetoScan:"
+                                echo -e "#\tAbhijeet Singh, Johan A. A. Nylander, Anna Schnürer, Bettina Müller" 
+                                echo -e "#\tHigh throughput sequencing and automated analysis of formyltetrahydrofolate" 
+                                echo -e "#\tsynthetase (FTHFS) gene amplicons to estimate acetogenic population dynamics,"
+                                echo -e "#\t<Journal Name>, Volume <2019>, <2019>, <webadress>\n"
+                                
+                                echo -e "#\tAcetoBase:"
+                                echo -e "#\tAbhijeet Singh, Bettina Müller, Hans-Henrik Fuxelius, Anna Schnürer" 
+                                echo -e "#\tAcetoBase: a functional gene repository and database for"
+                                echo -e "#\tformyltetrahydrofolate synthetase sequences,"
+                                echo -e "#\tDatabase, Volume 2019, 2019, baz142, https://doi.org/10.1093/database/baz142"
+                                exit
+                                ;;        
+                                
+                        X)
+                                echo -e "#\tAcetoScan commands:\n"
+                                echo -e "\t\tacetoscan\t- for complete processing of raw illumina MiSeq output data"
+                                echo -e "\t\tacetocheck\t- for processing fasta sequences and filtering out non-target sequences"
+                                echo -e "\t\tacetotax\t- acetocheck + taxonomic assignments"
+                                echo -e "\t\tacetotree\t- acetotax + phylogenetic tree generation"
+                                exit
+                                ;;        
 
                         *)
                                 usage
@@ -300,6 +336,15 @@ else
         echo -e "\n#\tMinimum cluster size: ${YELLOW}$cluster_size${RESTORE}"
 fi
 
+###		Checking evalue
+
+if [ "$evalue" == "" ];then
+        evalue="$evalue_def"
+        echo -e "\n#\tUsing default evalue: ${YELLOW}${evalue_def}${RESTORE}"
+else
+        echo -e "\n#\tE-value: ${YELLOW}$evalue${RESTORE}"
+fi
+
 ###    Checking threshold validity
 
 MAXTHRESHOLD=1.01
@@ -438,10 +483,13 @@ find ${WKDIR}/output_data/ -type f -iname "Best*.fasta" -printf "%f\n" | while r
         do 
              awk '/^>/ {gsub(/.fa(sta)?$/,"",FILENAME);printf(">%s\n",FILENAME);next;} {print}' "${x}"
         done > All_best.fasta.tmp
-
+        
+###		Modifying the sample names that is the fasta headers too
+        
+sed 's/Best_//g;s/_trimmed_R1//g' All_best.fasta.tmp > All_best.fasta.tmp2
 ###     Formating input for vsearch
 
-perl -npe 'if(!/^>/){s/\S{60}/$&\n/g};{s/-/_/g}' All_best.fasta.tmp > All_best.fasta
+perl -npe 'if(!/^>/){s/\S{60}/$&\n/g};{s/-/_/g}' All_best.fasta.tmp2 > All_best.fasta
 
 #       closing spinner for Preprocessing
 	echo -ne "Done\n"        
@@ -468,6 +516,7 @@ echo -e "\n#\tBegin clustering at ${LRED}$cluster_threshold %${RESTORE}"
                 --derep_fulllength "${WKDIR}/output_data/trimmed/All_best.fasta" \
                 --output "${WKDIR}/output_data/trimmed/VSEARCH/best_derep.fasta" \
                 --sizeout \
+                --fasta_width 0 \
                 --minuniquesize "${cluster_size}" \
                 --relabel Unique \
                 --uc "${WKDIR}/output_data/trimmed/VSEARCH/derep.uc" \
@@ -477,7 +526,8 @@ echo -e "\n#\tBegin clustering at ${LRED}$cluster_threshold %${RESTORE}"
 
         echo -e "\n#\t${YELLOW}Removing chimera${RESTORE}\n"
         vsearch \
-                --uchime_denovo "${WKDIR}/output_data/trimmed/VSEARCH/best_derep.fasta" \
+                --uchime_ref "${WKDIR}/output_data/trimmed/VSEARCH/best_derep.fasta" \
+                --db "/home/$user/acetoscan/acetobase/AcetoBase.fasta" \
                 --sizein \
                 --sizeout \
                 --chimeras "${WKDIR}/output_data/trimmed/VSEARCH/chimera.fasta" \
@@ -522,7 +572,7 @@ echo -e "\n#\t${LRED}OBS: This might take a while!\n${RESTORE}"
                 -task blastx \
                 -max_target_seqs 1 \
                 -num_threads "${THREADS}" \
-                -evalue 1e-5 \
+                -evalue ${evalue} \
                 -out "${WKDIR}/output_data/trimmed/VSEARCH/blast_results_for_filtering" \
                 -outfmt "7 qseqid" 2> /dev/null
 
@@ -587,14 +637,14 @@ echo -e "\n#\t${LRED}OBS: This might take a while!${RESTORE}\n"
 
         cut -d ";" -f1 "${WKDIR}/output_data/trimmed/VSEARCH/filtered_OTU.fasta" > "${WKDIR}/output_data/trimmed/VSEARCH/FTHFS_OTU.fasta"
 
-        # assigning taxonomy by translated nucleotide query wait protein database
+        # assigning taxonomy by translated nucleotide query with protein database
         blastx \
                 -query "${WKDIR}/output_data/trimmed/VSEARCH/FTHFS_OTU.fasta" \
                 -db "/home/$user/acetoscan/acetobase/AcetoBase" \
                 -task blastx \
                 -max_target_seqs 1 \
                 -num_threads "${THREADS}" \
-                -evalue 1e-5 \
+                -evalue 1e-3 \
                 -out "${WKDIR}/output_data/trimmed/VSEARCH/OTU_blast.txt.tmp" \
                 -outfmt "6 qseqid saccver pident evalue qlen length bitscore qseq" 2> /dev/null
 
@@ -722,6 +772,13 @@ else
         
 fi
 
+###    Getting final information
+
+end=$(date +%s) # end time of script
+runtime=$(((end - start))) # calculate runtime
+processing_data_size=$(find "$input_dir" -iname "*_${reads}_001.fastq.gz" -print0 | du --files0-from=- -ch | grep "total" | cut -f1)
+echo -e "\n#\tacetoscan processed: ${YELLOW} $processing_data_size ${RESTORE} in ${YELLOW} ${runtime} ${RESTORE} seconds\n"
+
 ###	Moving logfile from previous initial working directory to acetoscan_result directory
 ###	And removing logfile from previous initial working directory
 
@@ -729,16 +786,8 @@ find ${CDIR} -name "acetoscan_log" -exec sed -r 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2}
 find ${WKDIR}/acetoscan_result/ -name "0_acetoscan_${DATE}.log" -exec sed -i -e '/ambiguous characters./,/done./{//!d};/STEP/d;/(thread/d;/Processing:/d;/Constructing a UPGMA tree/,/done./{//!d};/seconds: Top hits for/d;/Joined/d;/NNI round/d;/seconds: SPR round/d;/ML Lengths/d;/NNI round/d;/Optimizing GTR model/d;/Site likelihoods with/d;/ML split tests for/d' {} \;
 find ${CDIR} -name "acetoscan_log" -exec rm {} \;
 
-###    Getting final information
-
-end=$(date +%s) # end time of script
-runtime=$(((end - start))) # calculate runtime
-processing_data_size=$(find "$input_dir" -iname "*_${reads}_001.fastq.gz" -print0 | du --files0-from=- -ch | grep "total" | cut -f1)
-echo -e "\n#\tAcetoscan processed: ${YELLOW} $processing_data_size ${RESTORE} in ${YELLOW} ${runtime} ${RESTORE} seconds\n"
-
 ### Greeting
 
 echo -e "\n#\t${YELLOW}${user}${RESTORE}, Thanks for using ${YELLOW}\"AcetoScan\"${RESTORE}\n\n###"
 
 ###    End of script
-
